export const INITIALIZE_PAGELIST = "INITIALIZE_PAGELIST";
export const GET_PAGELIST_MOST_RECENT = "GET_PAGELIST_MOST_RECENT";
export const GET_PAGES = "GET_PAGES";
export const CHANGE_EXP_DATE = "CHANGE_EXP_DATE";
export const GET_TOP_MOST_RECENT = 5;
